spring.application.name=cinegraph

server.port=8080

cognodb.uri=${COGNODB_URI}
cognodb.username=${COGNODB_USERNAME:cognodb}
cognodb.password=${COGNODB_PASSWORD}

management.endpoints.web.exposure.include=health
